### ISSUE TITLE
its nice but..

### ISSUE THREAD

**Issue by Odysseus1987** [vashin1/LineageUI#1]
How is this difference then Pfui ? 

Im a Pfui user atm , what did you add / change.  I couldnt see many differences.

**Comment by vashin1** [comment]
Right now mainly font's and raid frame sizing. Also changed the panel sizing for "zone" text.  

At first I just cherry picked commits and manually merged them into his latest release because I was under the impression that the -Master branch was the test branch and that everyday users should be using Releases. I wanted to bring those users the latest features and bug fixes without having to wait for the next release

Upon learning he uses a local test branch before uploading to his -Master on GitHub I decided to fork his entire project https://github.com/vashin1/pfUI and add personal touches to it there.
